name: Build Docker image containing required dependencies

on:
  workflow_call:
    outputs:
      build-image:
        description: "The name of the Docker image"
        value: ${{ jobs.build-image.outputs.build-image }}

jobs:
  build-image:
    name: Build Docker image containing required dependencies
    timeout-minutes: 120
    runs-on: ubuntu-latest
    outputs:
      build-image: ${{ steps.build-image.outputs.build-image }}
    steps:
      - uses: actions/checkout@v4
      - name: Enable Docker CLI experimental features
        run: echo "DOCKER_CLI_EXPERIMENTAL=enabled" >> $GITHUB_ENV
      - name: Docker login to GitHub Container Registry
        run: docker login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"
      - name: Build and push image if not present
        id: build-image
        run: |
          BUILD_IMAGE_HASH=$(echo -n "$(cat Cargo.lock .github/workflows/dependency-image.Dockerfile gradle/libs.versions.toml)" | md5sum | cut -c1-8)
          BUILD_IMAGE="ghcr.io/${{ github.repository }}/dependency-image:$BUILD_IMAGE_HASH"
          echo "build-image=$BUILD_IMAGE" >> $GITHUB_OUTPUT
          if ! docker manifest inspect $BUILD_IMAGE; then
            docker build -t $BUILD_IMAGE -f ./.github/workflows/dependency-image.Dockerfile .
            docker push $BUILD_IMAGE
          fi