name: Report test results

on:
  workflow_run:
    workflows: [ 'Build and run tests' ]
    types: [ completed ]

permissions:
  actions: read
  checks: write

jobs:
  report:
    name: Report test results
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-name:
          - examples-app
          - examples-audio-cpp-app
          - examples-custom-types
          - examples-tokio-blake3-app
          - examples-tokio-boring-app
          - gradle-plugin-tests
          - gradle-tests
          - uniffi-tests
          - uniffi-tests-gir
          - uniffi-tests-oc
          - uniffi-tests-gir-oc
        environment:
          - windows
          - macos
          - macos-intel
          - linux
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        id: download
        continue-on-error: true
        with:
          name: junit-test-results-${{ matrix.test-name }}-${{ matrix.environment }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Report test results
        uses: mikepenz/action-junit-report@v5
        if: ${{ steps.download.outcome == 'success' }}
        with:
          check_name: 'JUnit test report (${{ matrix.test-name }}, ${{ matrix.environment }})'
          commit: ${{ github.event.workflow_run.head_sha }}
          report_paths: '**/test-results/*est/TEST-*.xml'