name: Report Docker test results

on:
  workflow_run:
    workflows: [ 'Build and run tests in Docker' ]
    types: [ completed ]

permissions:
  actions: read
  checks: write

jobs:
  report:
    name: Report Docker test results
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-name:
          - examples-app
          - examples-audio-cpp-app
          - examples-custom-types
          - examples-tokio-blake3-app
          - examples-tokio-boring-app
          - gradle-plugin-tests
          - gradle-tests
          - uniffi-tests
          - uniffi-tests-gir
          - uniffi-tests-oc
          - uniffi-tests-gir-oc
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: junit-test-results-${{ matrix.test-name }}-docker
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Report test results
        uses: mikepenz/action-junit-report@v5
        with:
          check_name: 'JUnit Docker test report (${{ matrix.test-name }})'
          commit: ${{ github.event.workflow_run.head_sha }}
          report_paths: '**/test-results/*est/TEST-*.xml'