name: Publish Gobley to Maven Central and crates.io

on:
  release:
    types: [ created ]

jobs:
  build-image:
    name: Build Docker image containing required dependencies
    uses: ./.github/workflows/dependency-image.yml
    secrets: inherit
    with:
      trigger-event: ${{ github.event_name }}
  publish:
    name: Publish Gobley to Maven Central and crates.io
    timeout-minutes: 120
    runs-on: ubuntu-latest
    needs: build-image
    strategy:
      matrix:
        publish-name:
          - gradle-plugins
          - cargo-packages
    steps:
      - uses: actions/checkout@v4
      - name: Enable Docker CLI experimental features
        run: echo "DOCKER_CLI_EXPERIMENTAL=enabled" >> $GITHUB_ENV
      - name: Docker login to GitHub Container Registry
        run: docker login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"
      - name: Publish Gobley
        run: |
          docker run --rm \
            -v "${GITHUB_WORKSPACE}":/home/pr-build-test/workspace \
            -w /home/pr-build-test/workspace \
            -e GOBLEY_CRATES_IO_API_TOKEN="${GOBLEY_CRATES_IO_API_TOKEN}" \
            -e ORG_GRADLE_PROJECT_mavenCentralUsername="${GOBLEY_MAVEN_CENTRAL_USERNAME}" \
            -e ORG_GRADLE_PROJECT_mavenCentralPassword="${GOBLEY_MAVEN_CENTRAL_PASSWORD}" \
            -e ORG_GRADLE_PROJECT_signingInMemoryKey="${GOBLEY_MAVEN_CENTRAL_SIGNING_KEY}" \
            -e ORG_GRADLE_PROJECT_signingInMemoryKeyId="${GOBLEY_MAVEN_CENTRAL_SIGNING_KEY_ID}" \
            -e ORG_GRADLE_PROJECT_signingInMemoryKeyPassword="${GOBLEY_MAVEN_CENTRAL_SIGNING_PASSWORD}" \
            ${{ needs.build-image.outputs.build-image }} \
            /usr/bin/pwsh -c ./.github/workflows/publish-${{ matrix.publish-name }}.ps1
        env:
          GOBLEY_CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
          GOBLEY_MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          GOBLEY_MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          GOBLEY_MAVEN_CENTRAL_SIGNING_KEY: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY }}
          GOBLEY_MAVEN_CENTRAL_SIGNING_KEY_ID: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_ID }}
          GOBLEY_MAVEN_CENTRAL_SIGNING_PASSWORD: ${{ secrets.MAVEN_CENTRAL_SIGNING_PASSWORD }}